name: Docker Image CI/CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-instance-1:
    name: Deploy to EC2 Instance 1
    runs-on: ubuntu-latest
    needs: []
    steps:
  
    - name: Validate required secrets for Instance 1
      run: |
        if [[ -z "${{ secrets.EC2_HOST1_AS }}" || -z "ec2-user" || -z "${{ secrets.EC2_SSH_KEY2 }}" || -z "diego232323a" ]]; then
          echo "Error: Missing one or more required secrets for Instance 1."
          exit 1
        fi

    - name: Deploy to EC2 - instance-1
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST1_AS }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY2 }}
        port: 22
        script: |
          # Actualizar el sistema y configurar Docker
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          
          # Descargar la nueva imagen y detener/eliminar el contenedor actual
          sudo docker pull diego232323a/rest_helloworld:latest
          sudo docker ps -q --filter "name=rest_helloworld" | grep -q . && \
            sudo docker stop rest_helloworld && sudo docker rm rest_helloworld || true
          
          # Ejecutar el nuevo contenedor
          sudo docker run -d --name rest_helloworld -p 80:80 diego232323a/rest_helloworld:latest

  deploy-instance-2:
    name: Deploy to EC2 Instance 2
    runs-on: ubuntu-latest
    needs: []
    steps:

    - name: Validate required secrets for Instance 2
      run: |
        if [[ -z "${{ secrets.EC2_HOST2_AS }}" || -z "ec2-user" || -z "${{ secrets.EC2_SSH_KEY2 }}" || -z "diego232323a" ]]; then
          echo "Error: Missing one or more required secrets for Instance 2."
          exit 1
        fi

    - name: Deploy to EC2 - instance-2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST2_AS }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY2 }}
        port: 22
        script: |
          # Actualizar el sistema y configurar Docker
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          
          # Descargar la nueva imagen y detener/eliminar el contenedor actual
          sudo docker pull diego232323a/rest_helloworld:latest
          sudo docker ps -q --filter "name=rest_helloworld" | grep -q . && \
            sudo docker stop rest_helloworld && sudo docker rm rest_helloworld || true
          
          # Ejecutar el nuevo contenedor
          sudo docker run -d --name rest_helloworld -p 80:80 diego232323a/rest_helloworld:latest

  deploy-instance-3:
    name: Deploy to EC2 Instance 3
    runs-on: ubuntu-latest
    needs: []
    steps:
    
    - name: Validate required secrets for Instance 3
      run: |
        if [[ -z "${{ secrets.EC2_HOST3_AS }}" || -z "ec2-user" || -z "${{ secrets.EC2_SSH_KEY2 }}" || -z "diego232323a" ]]; then
          echo "Error: Missing one or more required secrets for Instance 3."
          exit 1
        fi

    - name: Deploy to EC2 - instance-3
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST3_AS }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY2 }}
        port: 22
        script: |
          # Actualizar el sistema y configurar Docker
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          
          # Descargar la nueva imagen y detener/eliminar el contenedor actual
          sudo docker pull diego232323a/rest_helloworld:latest
          sudo docker ps -q --filter "name=rest_helloworld" | grep -q . && \
            sudo docker stop rest_helloworld && sudo docker rm rest_helloworld || true
          
          # Ejecutar el nuevo contenedor
          sudo docker run -d --name rest_helloworld -p 80:80 diego232323a/rest_helloworld:latest

  deploy-instance-4:
    name: Deploy to EC2 Instance 4
    runs-on: ubuntu-latest
    needs: []
    steps:
    
    - name: Validate required secrets for Instance 4
      run: |
        if [[ -z "${{ secrets.EC2_HOST4_AS }}" || -z "ec2-user" || -z "${{ secrets.EC2_SSH_KEY2 }}" || -z "diego232323a" ]]; then
          echo "Error: Missing one or more required secrets for Instance 4."
          exit 1
        fi

    - name: Deploy to EC2 - instance-4
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST4_AS }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY2 }}
        port: 22
        script: |
          # Actualizar el sistema y configurar Docker
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          
          # Descargar la nueva imagen y detener/eliminar el contenedor actual
          sudo docker pull diego232323a/rest_helloworld:latest
          sudo docker ps -q --filter "name=rest_helloworld" | grep -q . && \
            sudo docker stop rest_helloworld && sudo docker rm rest_helloworld || true
          
          # Ejecutar el nuevo contenedor
          sudo docker run -d --name rest_helloworld -p 80:80 diego232323a/rest_helloworld:latest