name: QA CI/CD

on:
  push:
    branches: [ "QA" ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from Git
      id: vars
      run: |
        # Obtener el hash corto del commit
        echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        # Crear una etiqueta de versión personalizada
        echo "version_tag=$(date +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_ENV  

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: diego232323a
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        # Construir las imágenes con múltiples etiquetas
        docker build . --tag diego232323a/rest-helloworld:latest 
        
        # Subir ambas etiquetas al DockerHub
        docker push diego232323a/rest-helloworld:latest

  deploy:
    name: Deploy on AWS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy first Instance
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST1 }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY1 }}
        port: 22
        script: |
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          sudo docker pull diego232323a/rest-helloworld:latest
          sudo docker ps -q --filter "name=rest-helloworld" | grep -q . && \
            sudo docker stop rest-helloworld && sudo docker rm rest-helloworld || true
          sudo docker run -d --name rest-helloworld -p 80:80 diego232323a/rest-helloworld:latest

    - name: Deploy second Instance
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST1 }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY1 }}
        port: 22
        script: |
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          sudo docker pull diego232323a/rest-helloworld:latest
          sudo docker ps -q --filter "name=rest-helloworld" | grep -q . && \
            sudo docker stop rest-helloworld && sudo docker rm rest-helloworld || true
          sudo docker run -d --name rest-helloworld -p 80:80 diego232323a/rest-helloworld:latest